### ISSUE TITLE
Function to save all model selection into cache (ask Antonia)

### ISSUE THREAD

**Issue by policybot2020** [Pandora-IsoMemo/CausalR#20]

**Comment by arunge** [comment]
@policybot2020 Similar to the importModule, there is a module for downloading and uploading model results (or only the model inputs):
- the UI is defined here:
  https://github.com/Pandora-IsoMemo/data-tools/blob/85708131d41f588f8c7e59834f58d7779d60bbc9/R/02-downAndUpload.R#L9
- the server here:
  https://github.com/Pandora-IsoMemo/data-tools/blob/85708131d41f588f8c7e59834f58d7779d60bbc9/R/02-downAndUpload.R#L30

You can find an example on how to use it here:

- the UI function:
  https://github.com/Pandora-IsoMemo/iso-app/blob/f7366c574c919bde7430616f00b6cc83980fad23/R/03-modelResults2D.R#L20

- the server function:
  https://github.com/Pandora-IsoMemo/iso-app/blob/f7366c574c919bde7430616f00b6cc83980fad23/R/03-modelResults2D.R#L473C3-L521C34

In [action](https://isomemoapp.com/app/iso-memo-app-beta) it looks like this:

![image](https://github.com/Pandora-IsoMemo/CausalR/assets/16759098/d48592fd-0497-4369-a8cc-8a24d724eafe)

Please note that the UI might change a bit in the future dependent on the needs. I can let you know about important updates.

- The first section (1) enables to upload a locally saved model that was downloaded (3) via this module in the past.
- The second section (2) enables to upload a model that is stored on github. This requires some infrastructure on github. In the [github repository of the respective app](https://github.com/Pandora-IsoMemo/iso-app/blob/f7366c574c919bde7430616f00b6cc83980fad23/R/03-modelResults2D.R#L480) whose name must be provided via the parameter `githubRepo`, in my case `githubRepo = "iso-app"`, one must define a folder for the model objects under the following path: `inst/app/predefinedModels`. A model file (.zip) that was downloaded before must be uploaded to that folder. Than it should be selectable via the UI.
- The third section (3) enables to download a model as a .zip file.

Please, try to test this module and let me know about any issues. I am not sure if errors are thrown if the folder on github is missing, or if than the input in (2) is just empty. I do not remember if I tested this.

It would be great if you first try to use the module and let me know about any detailed questions. Thanks!

**Comment by arunge** [comment]
It is also possible to use only individual parts of this module. You can find all respective (sub) modules in this file: https://github.com/Pandora-IsoMemo/data-tools/blob/main/R/02-downAndUpload.R

**Comment by arunge** [comment]
However, the **most recent option** is 
- to enable the "Import module" (1) to upload also model objects, and
- to only add the download module (2) to the app. 

This allows to additionally store and load model objects from **Pandora**!
Please check the app [Resouces](https://isomemoapp.com/app/resources-beta) for this!

![image](https://github.com/Pandora-IsoMemo/CausalR/assets/16759098/95ad2019-2a4e-4be4-82cf-32306429e270)

- UI: https://github.com/Pandora-IsoMemo/resources/blob/7f3b3d6824285e8f08f909d4a8f01b5e499403a0/R/01-ui.R#L19C1-L21C52
- Server: https://github.com/Pandora-IsoMemo/resources/blob/7f3b3d6824285e8f08f909d4a8f01b5e499403a0/R/01-server.R#L99C3-L113C35

Actually, this is the way to go! And this I will add also to all of my other apps.

**Comment by policybot2020** [comment]
Save the extension: naming convention
- zipC

**Comment by policybot2020** [comment]
# Antonia Runge Links to test import model function



https://github.com/Pandora-IsoMemo/resources/blob/7f3b3d6824285e8f08f909d4a8f01b5e499403a0/R/01-server.R#L99C3-L113C35

https://github.com/Pandora-IsoMemo/resources/blob/7f3b3d6824285e8f08f909d4a8f01b5e499403a0/R/02-modules-downAndUploadModel.R#L35


https://github.com/Pandora-IsoMemo/data-tools/tree/main/inst/app/predefinedModels

**Comment by policybot2020** [comment]
Hi @arunge ,

I have tried to implement the Pandora Platform Connection Module `importDataServer`. But still does not function. 

Here is my original code that works that is a react function and returns `df`:

Code (1):
```
 data <- reactive({
    req(input$file)
    inFile <- input$file
    if (endsWith(inFile$name, ".csv")) {
      df <- read.csv(inFile$datapath, header = input$header)
    } else if (endsWith(inFile$name, ".xlsx") || endsWith(inFile$name, ".xls")) {
      df <- read_excel(inFile$datapath)
    } else {
      return(NULL)
    }
    if (input$treat_dates){
      return(df)
    } else {
      df <- subset(df, select = c(y, x1))
      return(df)
    }
  })
```
here is the code you helped me develop which uses the `importDataServer` module which is inside Observe() function:
Code (2):
```

  importedDat <- importDataServer("pandora_dat")
  fileImport <- reactiveVal(NULL)
  observe({
    if (length(importedDat()) == 0 ||  is.null(importedDat()[[1]])) fileImport(NULL)
    req(length(importedDat()) > 0, !is.null(importedDat()[[1]]))
    df <- reactive({importedDat()[[1]]})
    valid <- validateImport(data, showModal = TRUE)
    if (!valid){
      showNotification("Import is not valid.")
      fileImport(NULL)
    } else {
      fileImport(df)
    }
    fileImport(df)
  }) %>% bindEvent(importedDat())
```

I have issues implementing this code above, because my original code (1) is a reactive function, and I don't know how to turn your code into a reactive function and return the dataframe, which I use later in server function `data()` to graph plots outputs:
For example:

- `matplot(data(), type = 'l', main = input$title, xlab = input$x_label, ylab = input$y_label)`

So, I need to turn the code (2) into a reactive function, so that I can use it in other server functions. 

I tried after the `  }) %>% bindEvent(importedDat())`:
using this....`data  <- reactive({return(df)})`

I have tried many times and cannot do it on my own, Can you give me some advice or recommendations? 

please advise me,

Jian

**Comment by arunge** [comment]
Hi @policybot2020 

The object `importedDat()` that is returned by the module is a `reactiveVal()`. If you set a [browser() and debug](https://shiny.posit.co/r/articles/improve/debugging/) the 
```R
  observe({ ... }) %>% 
    bindEvent(importedDat())
```
you can easily check what kind of data is returned by the module.

If the import does not fail, than the object `importedDat()` is a named list. It currently contains only one element.
- The name of this element is exactly the name of the file that was imported. In the case you need this information you can get it with: `names(importedDat())[1]`

### Import of data files: use the _default_ option: `importType = "data"`

- `importedDat()[[1]]` contains the imported data itself, usually a `data.frame`
- you can get the content of the imported data during debugging by calling:
  ```R
    importedDat()[[1]]
  ```
- you can assign the content to another variable with:
  ```R
    your_new_variable <- importedDat()[[1]]
  ```
- if you use the option `outputAsMatrix = TRUE` (by default this is `outputAsMatrix = FALSE`), the output will be a matrix and additional logic is applied to set column and row names of the output. Currently this is only relevant for the app [Resources](https://isomemoapp.com/app/resources-beta).
- Of course, you must apply your own logic inside
  ```R
      observe({ ... }) %>% 
        bindEvent(importedDat())
  ```
  Please, define your own function `validateImport()` to validate your import. This function is not part of the package `DataTools`.

I hope, this helped. Let me know if you have more questions.

**Comment by arunge** [comment]
@policybot2020 Please let me know of any progress regarding the import module. If you managed to use the module to import a data file, I would continue to explain how model objects can be downloaded and uploaded with modules from the DataTools package.

**Comment by policybot2020** [comment]
@isomemo  @arunge I have no progress, I have tried many ways. but still have no progress. here is a video that explains my issue: https://www.youtube.com/watch?v=efBVI1HapRM&t=50s

maybe you can help me review my code. This is under the branch `feat/pandoraUpload`

**Comment by isomemo** [comment]
@arunge @policybot2020 Antonia, please suggest schedules when we can meet with Jian to solve this. Please see also my emails on this.

**Comment by arunge** [comment]
@isomemo I can offer a meeting on Monday and sent an invitation to @policybot2020 .

**Comment by isomemo** [comment]
@arunge thanks, Antonia! At what times can you meet?

**Comment by isomemo** [comment]
@policybot2020 @arunge  thanks, Antonia! At what times can you meet?

**Comment by arunge** [comment]
@policybot2020 I opened a pull request regarding the import of data. Please test and merge the changes.

As I [mentioned](https://github.com/Pandora-IsoMemo/CausalR/issues/20#issuecomment-1752448948), understanding the differences between `reactive()`, `reactiveVal()` and `reactiveValues()` is crucial when developing in Shiny. Please, check https://mastering-shiny.org/reactivity-objects.html to become more familiar with the concept of reactivity.

In the meeting on Monday we can discuss how to proceed with the download of models and their upload.

**Comment by policybot2020** [comment]
#23 this pull request to as solved this saving model issue . now all models can be saved. @isomemo
