### ISSUE TITLE
CausalR: Start Local App failure

### ISSUE THREAD

**Issue by policybot2020** [Pandora-IsoMemo/CausalR#28]
@arunge 

I was testing the local version again with the Main Branch of `CausalR`, but I got an issue:

Step 1: Install CausalR from DRAT
```
> options(repos = c(getOption("repos"), PANDORA = "https://Pandora-IsoMemo.github.io/drat/"))
> install.packages("CausalR")
> library(CausalR)
> startApplication()
```
App Crashed with this message:
```
Listening on http://0.0.0.0:4242
Warning: Error in importDataServer: unused argument (options = importOptions(githubRepo = "CausalR"))
  39: server [/Library/Frameworks/R.framework/Versions/4.1/Resources/library/CausalR/app/app.R#236]
   2: runApp
   1: startApplication
Error in importDataServer("modelUpload", title = "Import Model", defaultSource = "file",  : 
  unused argument (options = importOptions(githubRepo = "CausalR"))
```

It is referring to this
https://github.com/Pandora-IsoMemo/CausalR/blob/ed8ff4eeea3befd7ce8585f1ea381293e96339d9/inst/app/app.R#L236

Should we just delete this line 242: "unused argument (options = importOptions(githubRepo = "CausalR"))" ?

**Comment by arunge** [comment]
Hi @policybot2020 ! No, the issues occurs simply of a too old version of DataTools. Please, update your DataTools installation. I updated the Description file respectively. Please pull updates from [main](https://github.com/Pandora-IsoMemo/CausalR/commit/e4a026513c874d78f9ea423e342e7ad73f979671)/beta.
